# License: MIT

[profile.default]
src = "contracts"
out = "out"
libs = ["dependencies", "mocks", "mocks", "local"]
test = "test"
cache_path = "cache_forge"
broadcast = "broadcast"
script = "scripts"
allow_paths = ["./contracts", "./dependencies", "./local", "./trst"]
auto_detect_remappings = true
solc_version = "0.8.29"
optimizer = true
optimizer_runs = 200
eth_rpc_url = "http://localhost:8545"
rpc_endpoints = { local = "http://localhost:8545" }
verbosity = 3
ffi = true
via_ir = false

[profile.scripts]
src = "scripts"
via_ir = true

[dependencies]
forge-std = "1.9.6"
smartcontractkit-chainlink-brownie-contracts = "1.3.0"
"@openzeppelin-contracts" = "5.3.0"
